### ISSUE TITLE
4.3 weeks per month

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-FinancialStatment#1]
I noticed going through this that the interview uses 4 weeks per month.  For this form, there should always be 4.3 weeks per month, both in the outward text the user sees and in internal calculations of income.

@purplesky2016

**Comment by purplesky2016** [comment]
Thanks! I can change the weeks to 4.3 in the calculations. As for the text, I'll leave it to you and @CaroRob , so please feel free to change any user-facing text in this whole project.

**Comment by purplesky2016** [comment]
What about converting annual amount to weekly amount? Do we use annualAmt/52, or /51.6, or what is a good denominator?

**Comment by kateleebarry** [comment]
52 is fine for annual!

**Comment by purplesky2016** [comment]
Changes pushed to github.
