### ISSUE TITLE
SSN not mandatory 

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-FinancialStatment#2]
Social security number should be optional.  People without SSNs are required to use this form also.  Also, we should only accept last four digits with a character limit preventing someone from inputting whole SSN.  

@purplesky2016

**Comment by purplesky2016** [comment]
Ah, I think I got that language from the court website when I downloaded the pdf form, but you know better.  Again I'll leave all the text to you and @CaroRob .

I'll change the the ssn input to text limited to 4 characters (set both minlength and maxlength to 4).

**Comment by purplesky2016** [comment]
Changes pushed to github.
