### ISSUE TITLE
error after entering number of debts

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-FinancialStatment#7]
error: interview has an error. There was a reference to a variable 'i' that could not be looked up in the question file (for language 'en') or in any of the files incorporated by reference into the question file.

final block of error message:
```
`Tried to run block at 0.01146s
(from FS-debts.yml)

if: ynDebts
code: |    
  debts[i].name.text
  debts[i].date
  debts[i].complete = True   
  
  count = 0
  for y in debts:
    count += 1
  if count == debts.target_number:
    debtsDone = True

  #Accumulate debts value after the last debt's info collected.
  if debtsDone:       
    TotalDebtDue = 0
    TotalDebtPmt = 0
    debts[0].wklyPmt = 0   
    for y in debts:         
      tmpAnnPmt = int(y.PayFrequency) * y.payment
      y.wklyPmt = round(tmpAnnPmt/52, 0)
      TotalDebtDue += y.amtDue
      TotalDebtPmt += y.wklyPmt 
Needed definition of i at 0.01153s
````

**Comment by purplesky2016** [comment]
Please provide what input you used regarding debts for me to replicate the error and track the cause.

**Comment by CaroRob** [comment]
I think it was the screen that asked if I have any debts, I said yes. 
It asked how many - on same screen.
I said 2. 
I **think** that was the screen - questions don't have id's so it's more difficult to name them.

**Comment by purplesky2016** [comment]
Fixed the error and added the screen ids.
